name: Overleaf Sync with Git
on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Old Artifacts
      uses: actions/github-script@v6
      id: artifact
      with:
        script: |
          const res = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
    
          res.data.artifacts
            .forEach(({ id }) => {
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: id,
              })
            })

    - uses: actions/checkout@v2
      with:
        path: repo/

    - name: Run entrypoint.sh
      run: |
        cd repo/
        chmod +x ./entrypoint.sh
        ./entrypoint.sh ../tmp
      env:
        OVERLEAF_PROJECT_ID: ${{ secrets.OVERLEAF_PROJECT_ID }}
        OVERLEAF_COOKIE: ${{ secrets.OVERLEAF_COOKIE }}
        OVERLEAF_HOST: ${{ secrets.OVERLEAF_HOST }}

    - name: Sync files and commit changes
      run: |
        cd repo
        rm -rf ./paper
        mkdir -p ./paper
        cp -r ../artifacts/* ./paper
        git config user.name "Overleaf Sync Bot"
        git config user.email "actions@github.com"

        # 尝试将 entrypoint.sh 添加到暂存区
        git add entrypoint.sh || true

        git add paper/

        # 拉取远程更改并处理可能的冲突
        git pull origin main --rebase || true

        # 检查是否有更改可以提交
        if [[ $(git diff --cached --stat) != '' ]]; then
          git commit -m "Sync with Overleaf remote" && git push
        else
          echo 'No changes to commit'
        fi
